# Generated by Django 4.2.7 on 2024-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CobaltModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=18)),
                ('gear', models.CharField(choices=[('m', 'Manual'), ('a', 'Auto')], max_length=5)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GentraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=18)),
                ('gear', models.CharField(choices=[('m', 'Manual'), ('a', 'Auto')], max_length=5)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MalibuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=18)),
                ('gear', models.CharField(choices=[('m', 'Manual'), ('a', 'Auto')], max_length=5)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NexiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=18)),
                ('gear', models.CharField(choices=[('m', 'Manual'), ('a', 'Auto')], max_length=5)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
